2022-03-03 13:34:06,485 - instabot version: 0.117.0 (bot) - INFO - Instabot version: 0.117.0 Started
2022-03-03 13:34:06,486 - instabot version: 0.117.0 (bot) - DEBUG - Bot imported from C:\Python39\lib\site-packages\instabot\bot\bot.py
2022-03-03 13:34:06,488 - instabot version: 0.117.0 (api_login) - INFO - Not yet logged in starting: PRE-LOGIN FLOW!
2022-03-03 13:34:06,837 - instabot version: 0.117.0 (api) - DEBUG - POST to endpoint: accounts/get_prefill_candidates/ returned response: <Response [200]>
2022-03-03 13:34:07,065 - instabot version: 0.117.0 (api) - DEBUG - POST to endpoint: qe/sync/ returned response: <Response [200]>
2022-03-03 13:34:07,275 - instabot version: 0.117.0 (api) - DEBUG - POST to endpoint: launcher/sync/ returned response: <Response [200]>
2022-03-03 13:34:07,460 - instabot version: 0.117.0 (api) - DEBUG - POST to endpoint: accounts/contact_point_prefill/ returned response: <Response [200]>
2022-03-03 13:34:11,315 - instabot version: 0.117.0 (api) - DEBUG - POST to endpoint: accounts/login/ returned response: <Response [400]>
2022-03-03 13:34:11,315 - instabot version: 0.117.0 (api) - DEBUG - Responsecode indicates error; response content: b'{"message":"challenge_required","challenge":{"url":"https://i.instagram.com/challenge/AXG8foLFm5yVFlsvNyn0j188tx1yqCCucLD5edchobrtjjIZ-8d3VqOOSOCM7TSdTI9Dog/3ArUQFauyX/","api_path":"/challenge/AXG8foLFm5yVFlsvNyn0j188tx1yqCCucLD5edchobrtjjIZ-8d3VqOOSOCM7TSdTI9Dog/3ArUQFauyX/","hide_webview_header":true,"lock":true,"logout":false,"native_flow":true,"flow_render_type":0},"status":"fail","error_type":"checkpoint_challenge_required"}'
2022-03-03 13:34:11,315 - instabot version: 0.117.0 (api) - ERROR - Request returns 400 error!
2022-03-03 13:34:11,316 - instabot version: 0.117.0 (api) - INFO - Instagram's error message: challenge_required
2022-03-03 13:34:11,317 - instabot version: 0.117.0 (api) - INFO - Error type: checkpoint_challenge_required
